// <auto-generated />
using FinalFantasy.RepositoryEF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinalFantasy.RepositoryEF.Migrations
{
    [DbContext(typeof(FinalFantasyContext))]
    [Migration("20210709073539_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinalFantasy.Core.Entities.Arma", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Danno")
                        .HasColumnType("int");

                    b.HasKey("Nome");

                    b.ToTable("Arma");

                    b.HasData(
                        new
                        {
                            Nome = "Ascia",
                            Danno = 8
                        },
                        new
                        {
                            Nome = "Mazza",
                            Danno = 5
                        },
                        new
                        {
                            Nome = "Spada",
                            Danno = 10
                        },
                        new
                        {
                            Nome = "Bastone Magico",
                            Danno = 10
                        },
                        new
                        {
                            Nome = "Bacchetta",
                            Danno = 5
                        },
                        new
                        {
                            Nome = "Arco e Frecce",
                            Danno = 8
                        },
                        new
                        {
                            Nome = "Arco",
                            Danno = 7
                        },
                        new
                        {
                            Nome = "Clava",
                            Danno = 5
                        },
                        new
                        {
                            Nome = "Divinazione",
                            Danno = 15
                        },
                        new
                        {
                            Nome = "Fulmine",
                            Danno = 10
                        },
                        new
                        {
                            Nome = "Tempesta",
                            Danno = 8
                        },
                        new
                        {
                            Nome = "Tempesta Oscura",
                            Danno = 15
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Eroe", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArmaNome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoriaEroe")
                        .HasColumnType("int");

                    b.Property<string>("GiocatoreNickname")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Livello")
                        .HasColumnType("int");

                    b.Property<int>("PuntiEsperienza")
                        .HasColumnType("int");

                    b.HasKey("Nome");

                    b.HasIndex("ArmaNome");

                    b.HasIndex("GiocatoreNickname");

                    b.ToTable("Eroe");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Giocatore", b =>
                {
                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Nickname");

                    b.ToTable("Giocatore");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Mostro", b =>
                {
                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ArmaNome")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoriaMostro")
                        .HasColumnType("int");

                    b.Property<int>("Livello")
                        .HasColumnType("int");

                    b.HasKey("Nome");

                    b.HasIndex("ArmaNome");

                    b.ToTable("Mostro");

                    b.HasData(
                        new
                        {
                            Nome = "Qwerty",
                            ArmaNome = "Arco",
                            CategoriaMostro = 0,
                            Livello = 1
                        },
                        new
                        {
                            Nome = "Satan",
                            ArmaNome = "Fulmine",
                            CategoriaMostro = 1,
                            Livello = 2
                        },
                        new
                        {
                            Nome = "Mefisto",
                            ArmaNome = "Tempesta Oscura",
                            CategoriaMostro = 1,
                            Livello = 3
                        });
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Eroe", b =>
                {
                    b.HasOne("FinalFantasy.Core.Entities.Arma", "Arma")
                        .WithMany("Eroi")
                        .HasForeignKey("ArmaNome");

                    b.HasOne("FinalFantasy.Core.Entities.Giocatore", "Giocatore")
                        .WithMany("Eroi")
                        .HasForeignKey("GiocatoreNickname");

                    b.Navigation("Arma");

                    b.Navigation("Giocatore");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Mostro", b =>
                {
                    b.HasOne("FinalFantasy.Core.Entities.Arma", "Arma")
                        .WithMany("Mostri")
                        .HasForeignKey("ArmaNome");

                    b.Navigation("Arma");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Arma", b =>
                {
                    b.Navigation("Eroi");

                    b.Navigation("Mostri");
                });

            modelBuilder.Entity("FinalFantasy.Core.Entities.Giocatore", b =>
                {
                    b.Navigation("Eroi");
                });
#pragma warning restore 612, 618
        }
    }
}
